/**
 * @fileoverview Personality.ts
 * @author Luca Warmenhoven
 * @date Created on Friday, October 25 - 16:44
 */

/**
 * The personality of a user.
 * This class represents the personality of a user, which can be used to
 * generate more accurate and personalized responses.
 * The personality of a user can be generated by the assistant, or can be
 * provided by the user.
 */
export class Personality {



}
